export enum MethodActionTypes {
  FETCH_SINGLE_METHOD = "FETCH_SINGLE_METHOD",
  FETCH_SINGLE_METHOD_SUCCESS = "FETCH_SINGLE_METHOD_SUCCESS",
  FETCH_SINGLE_METHOD_ERROR = "FETCH_SINGLE_METHOD_ERROR",
}
