export enum FaultActionTypes {
  FETCH_FAULTS = "FETCH_FAULTS",
  FETCH_FAULTS_SUCCESS = "FETCH_FAULTS_SUCCESS",
  FETCH_FAULTS_ERROR = "FETCH_FAULTS_ERROR",

  FETCH_FAULT = "FETCH_FAULT",
  FETCH_FAULT_SUCCESS = "FETCH_FAULT_SUCCESS",
  FETCH_FAULT_ERROR = "FETCH_FAULT_ERROR",
}
