export enum SolutionActionTypes {
  FETCH_SOLUTIONS = "FETCH_SOLUTIONS",
  FETCH_SOLUTIONS_SUCCESS = "FETCH_SOLUTIONS_SUCCESS",
  FETCH_SOLUTIONS_ERROR = "FETCH_SOLUTIONS_ERROR",

  FETCH_SINGLE_SOLUTION = "FETCH_SINGLE_SOLUTION",
  FETCH_SINGLE_SOLUTION_SUCCESS = "FETCH_SINGLE_SOLUTION_SUCCESS",
  FETCH_SINGLE_SOLUTION_ERROR = "FETCH_SINGLE_SOLUTION_ERROR",
}
