export enum StudyActionTypes {
  FETCH_STUDY = "FETCH_STUDY",
  FETCH_STUDY_SUCCESS = "FETCH_STUDY_SUCCESS",
  FETCH_STUDY_ERROR = "FETCH_STUDY_ERROR",

  FETCH_STUDIES = "FETCH_STUDIES",
  FETCH_STUDIES_SUCCESS = "FETCH_STUDIES_SUCCESS",
  FETCH_STUDIES_ERROR = "FETCH_STUDIES_ERROR",
}
