export enum CauseActionTypes {
  FETCH_CAUSES = "FETCH_CAUSES",
  FETCH_CAUSES_SUCCESS = "FETCH_CAUSES_SUCCESS",
  FETCH_CAUSES_ERROR = "FETCH_CAUSES_ERROR",

  FETCH_CAUSE = "FETCH_CAUSE",
  FETCH_CAUSE_SUCCESS = "FETCH_CAUSE_SUCCESS",
  FETCH_CAUSE_ERROR = "FETCH_CAUSE_ERROR",
}
